### ISSUE TITLE
怎么使用啊，小白求个demo

### ISSUE THREAD

**Issue by sixgodfan** [taoran1401/lua-DDOS#1]
怎么使用啊，小白求个demo以及参数说明好自己根据业务修改数值大小，谢谢

**Comment by naroat** [comment]
这个脚本的详细用法已经更新到REDEME, 这个脚本的用法在nginx配置中加载lua脚本来处理的，动态控制是通过程序在redis里面修改指定的值实现的，详情看REDEME; 如果你不是这种场景，而是需要程序调用脚本来实现可以参考：https://www.cnblogs.com/xyj179/p/10717533.html
